baseURL = "https://serverless.land/"
languageCode = "en-us"
title = "Serverless Land"
copyright = "Mikhail Shilkov - All rights reserved"

summaryLength = 25
enableEmoji = true

[params]
#  logo = "/images/logo.png"
  description ="Open-source, open-data benchmarks of managed cloud services"

[params.author]
  name = "Mikhail Shilkov"
  thumbnail = "/images/author.jpg"
  
[params.index]
  picture = "/images/author.jpg"
  title = "Mikhail Shilkov"
  alertbar = false

[params.social]
  github = "serverlessland"
  twitter = "serverlessland"

## Main Menu
[[menu.main]]
    name = "COLD STARTS"
    weight = 100
    identifier = "coldstarts"
    url = "/coldstarts/"
[[menu.main]]
    name = "BLOG"
    weight = 200
    identifier = "blog"
    url = "/blog/"